// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DataIngestionLib.EFModels;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DataIngestionLib.EFModels
{
    public partial interface IKnowledgeBaseContextProcedures
    {
        Task<List<Search_FullTextResult>> Search_FullTextAsync(string query, int? topN, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Search_HybridResult>> Search_HybridAsync(string query, byte[] queryEmbedding, int? topN, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Search_SemanticKeyPhrasesResult>> Search_SemanticKeyPhrasesAsync(int? documentId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<Search_VectorResult>> Search_VectorAsync(string queryEmbedding, int? topN, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
