// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DataIngestionLib.EFModels;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DataIngestionLib.EFModels
{
    public partial class KnowledgeBaseContext
    {
        private IKnowledgeBaseContextProcedures _procedures;

        public virtual IKnowledgeBaseContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new KnowledgeBaseContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IKnowledgeBaseContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class KnowledgeBaseContextProcedures : IKnowledgeBaseContextProcedures
    {
        private readonly KnowledgeBaseContext _context;

        public KnowledgeBaseContextProcedures(KnowledgeBaseContext context)
        {
            _context = context;
        }

        public virtual async Task<List<Search_FullTextResult>> Search_FullTextAsync(string query, int? topN, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Query",
                    Size = 8000,
                    Value = query ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "TopN",
                    Value = topN ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Search_FullTextResult>("EXEC @returnValue = [dbo].[Search_FullText] @Query = @Query, @TopN = @TopN", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<Search_HybridResult>> Search_HybridAsync(string query, byte[] queryEmbedding, int? topN, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Query",
                    Size = 8000,
                    Value = query ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "QueryEmbedding",
                    Size = 6152,
                    Value = queryEmbedding ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarBinary,
                },
                new SqlParameter
                {
                    ParameterName = "TopN",
                    Value = topN ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Search_HybridResult>("EXEC @returnValue = [dbo].[Search_Hybrid] @Query = @Query, @QueryEmbedding = @QueryEmbedding, @TopN = @TopN", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<Search_SemanticKeyPhrasesResult>> Search_SemanticKeyPhrasesAsync(int? documentId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "DocumentId",
                    Value = documentId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Search_SemanticKeyPhrasesResult>("EXEC @returnValue = [dbo].[Search_SemanticKeyPhrases] @DocumentId = @DocumentId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<Search_VectorResult>> Search_VectorAsync(string queryEmbedding, int? topN, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "QueryEmbedding",
                    Size = -1,
                    Value = queryEmbedding ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                new SqlParameter
                {
                    ParameterName = "TopN",
                    Value = topN ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<Search_VectorResult>("EXEC @returnValue = [dbo].[Search_Vector] @QueryEmbedding = @QueryEmbedding, @TopN = @TopN", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
