// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DataIngestionLib.EFModels;

public partial class KnowledgeBaseContext : DbContext
{
    public KnowledgeBaseContext(DbContextOptions<KnowledgeBaseContext> options)
        : base(options)
    {
    }

    public virtual DbSet<RemoteRag> RemoteRags { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<RemoteRag>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RemoteRA__3214EC075F4501BD");

            entity.ToTable("RemoteRAG");

            entity.HasIndex(e => e.Embedding, "VIX_RemoteRAG_embedding");

            entity.Property(e => e.Description)
                .IsRequired()
                .HasColumnName("description");
            entity.Property(e => e.DocumentId)
                .HasDefaultValueSql("(newid())", "DF__RemoteRAG__DocId__4F47C5E3")
                .HasColumnName("document_id");
            entity.Property(e => e.Embedding)
                .HasMaxLength(1024)
                .HasColumnName("embedding");
            entity.Property(e => e.Keywords)
                .HasMaxLength(500)
                .HasColumnName("keywords");
            entity.Property(e => e.MsDate).HasColumnName("ms_date");
            entity.Property(e => e.OgUrl)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("og_url");
            entity.Property(e => e.Summary).HasColumnName("summary");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(450)
                .HasColumnName("title");
            entity.Property(e => e.TokenCount).HasColumnName("token_count");
            entity.Property(e => e.UpdatedAt).HasColumnName("updated_at");
            entity.Property(e => e.Version).HasColumnName("version");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}