// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataIngestionLib.EFModels
{
    public partial class Search_VectorResult
    {
        public int id { get; set; }
        [StringLength(450)]
        public string title { get; set; }
        [StringLength(2147483647)]
        public string summary { get; set; }
        [StringLength(500)]
        public string keywords { get; set; }
        [StringLength(500)]
        public string og_url { get; set; }
        public double? vector_distance { get; set; }
    }
}
